name: Code Quality
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'
jobs:
  code-quality:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        # operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        # php-versions: ['8.1', '8.2', '8.3', '8.4', '8.5']
        operating-system: ['ubuntu-latest']
        php-versions: ['8.4']
    steps:
      - name: Force linux line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, json, grpc, opentelemetry
          ini-values: post_max_size=512M, max_execution_time=180
          coverage: xdebug
          tools: phpcs, phpstan, phpunit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --dev

      - name: Build Vite manifest
        run: |
          npm install
          npm run build

      - name: Run PHP Codesniffer
        run: phpcs

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        # We only care about PHP 8.4 (latest stable) for our code coverage report
        if: matrix.php-versions == 8.4
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: code-quality
    # Only build docker images on pushes to master, develop and tags
    if:
      (
        startsWith(github.ref, 'refs/tags') ||
        github.ref == format('refs/heads/{0}', 'master') ||
        github.ref == format('refs/heads/{0}', 'develop')
      ) &&
      github.event_name != 'pull_request'
    steps:
      - name: Build and Push Docker Image
        uses: ./.github/workflows/build-and-push-docker.yml
